// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycxefjpuspdziodijftc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljeGVmanB1c3BkemlvZGlqZnRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODQ1NTksImV4cCI6MjA2MTk2MDU1OX0.TmXwLu64JDJaQ5y1BIUS0RGXpiFpupnLll9cz2Q6Lg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);